# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://github.com/BigstickCarpet/eslint-config-modular

root: true

extends:
  - modular/best-practices
  - modular/style
  - modular/browser
  - modular/node
  - modular/es5
  - modular/test

globals:
  # BDD globals
  describe: true
  it: true
  before: true
  after: true
  beforeEach: true
  afterEach: true

  # Chai.js globals
  chai: true
  assert: true
  expect: true

  # SuperAgent globals
  response: true

  # Postman globals
  postman: false
  tests: false
  tv4: false
  xml2Json: false
  request: false
  responseBody: false
  responseCode: false
  responseHeaders: false
  responseCookies: false
  responseTime: false
