# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://github.com/BigstickCarpet/eslint-config-modular

extends:
  - modular/best-practices
  - modular/style
  - modular/browser
  - modular/node
  - modular/es5
